language: ruby
sudo: false
cache: bundler
rvm:
- 2.2.2

before_install: 
  - cd ./Documentation

install: 
  - bundle install

script:  
  - bundle exec jekyll build
  - bundle exec htmlproofer --help
  - bundle exec htmlproofer ./_site --disable-external --allow-hash-href
  
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
