language: ruby
sudo: false
cache: bundler
rvm:
- 2.5.3
before_install:
- gem install bundler
- cd ./Documentation
install:
- bundle install
script:
- bundle exec jekyll build
- rm ./_site/titlepage/index.html
- rm ./_site/tocpage/index.html
- bundle exec htmlproofer ./_site --allow-hash-href --disable-external
- cd ../Ruby/
- ruby ftpfiles.rb $FTP_USER $FTP_PWD
after_success:

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - FTP_USER=dyrxzbox@quantsa.org  
  - secure: ii1Q/JRxWaTYxtpjyP3HTjOMsK7XBarybbhw1Qv28hBsF14pXEUFeCgTiN8H67xxN9ekuUi3Mg4pKVgCmygnnAfcDPWD9NsKR8isIIKPLbuiTk9O0JVzNy5tG5dNqHeIUSCdbVwPmqPJdxlSdQKFwRlqPm34zhfrrqlxaLSUEkrSz75QHpi+WnB4lF8WOLlcm5ug7iwvqI1tXBk0paxdvflXIdguajiVTCq3PjYTCFv5BK+iRF/jOXhNbsD3uOHG2ohvifK8Wd5cKnBCRaUg14V8cYOckw82IfsKZPS8hUjrQkrodzqMw8bftaJnBbBYlIw/aMhBUn0fZ4UlE552QABhKtPHlC79yj6052w0BefCgZW9MUcyps9F51Tyj4PMvkQBuV+Gf2SFFLA70we9bkYC+RWyEMeNrt7N84ao0KHgYPkMuqKubmnCVwxIFumiC1iSe1XHV6Md1l2gXJUr3r01ElC7Qw0S2VZ9FmvbKaQc+n4KmMKDa8sCD+LpItygotx8ZQEt10raqHur4kjzCaTc6X+TpNWfEpX3vmfzwINapC0A3deTl228nmWTbiNTY75nurkjRxzQSFajVZxejEw7Cy/vMYSedZ68POT60d7+/uLbFPmU/YsKP9M25H+dB1P4M9czNhnszNAbTEu/6y9ssUfWcrE0t21PQO+uUfs=
