language: ruby
sudo: false
cache: bundler
rvm:
- 2.2.2

before_install: 
  - cd ./Documentation

install: 
  - bundle install

script:  
  - bundle exec jekyll build  
  - rm ./_site/titlepage/index.html # I don't know how to stop this file and the next from being generated, but they are filled with path errors that confuse htmlproofer
  - rm ./_site/tocpage/index.html
  - bundle exec htmlproofer ./_site --allow-hash-href --disable-external 
  
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  
