language: ruby
sudo: false
cache: bundler
rvm:
- 2.2.2
before_install:
- npm install vinyl-ftp gulp-util minimist --save-dev
- cd ./Documentation
install:
- bundle install
script:
- bundle exec jekyll build
- rm ./_site/titlepage/index.html
- rm ./_site/tocpage/index.html
- bundle exec htmlproofer ./_site --allow-hash-href --disable-external

after_success:
#- "curl --ftp-create-dirs -T ./_site/CreateCDS.html -u $FTP_USER:$FTPPWD ftp://quantsa.org/test/"
- cd ..
- gulp
- gulp deploy --user $FTP_USER --password $FTPPWD

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - "FTP_USER=James2@quantsa.org"
  - secure: UXcgKoJd9jSTRQXcVwnPh++t5VxuuTK3PC/piZoelC5XXEzbeD478EDa1uhoJkPJTJb7CnTM3mGAlvZ5U5N6SGH67J4T0FB8g+xzCyK+g9786E4dgpBu3XYjZ7/6pVnTcZLx6mq8/xrBaWvPj1HgjXjyGnWBFEcwGREQU9y/vF8zfy7lmBg3WXnLDBKCKwX/Lt+tKBorIGL00WsYDK6JWKD1QU+MOKJyN1qFlSBWH3KCRjm7+gk0VuQ2QaBZELW/P/0i14cIMWrE3iftC6yWz7YZckRAnk4RpwyG5DzhgBs9sCcUl8u9pWA1AMtOamKXKT/nNbIp2PIuUzNt4mXQFIh9xZP3msTgryzERx3b+CIBLp83RZ9TU/NXnnu2RS5iCZIkGKI7mSAb0902GWRqxshJ+TDUx5vJNMhZYPNHHvPxmhUfejfO0Mx+oIX5T2ATWF9iWSuV2DhQyW/Uan5mgXcSw4plCw0h5QlqLGmNSBkbFc0r0aOmysFD3uPhvS30xJtUidvEnI67+aOJQpTjiqO7QWNMX3Ljcz+pyMGz5KJY3yCM+4Twh4rDvvAZ7PZYp/CSudKjXhk+N8+tcsSidx5z1e8wQlQdCtKJMpvPkWvJw8DowQ1VUWRy4zjl9Z7r6UoAXmsnolLB8QgqoOvpbbnCsJ2fO9s7lku2udeOSKA=
