//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuantSAInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuantSAInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Accord {
            get {
                object obj = ResourceManager.GetObject("Accord", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date dealStartDate = new Date(2016, 1, 1); // The issue date of the scheme
        ///Date dealEndDate = dealStartDate.AddTenor(Tenor.Years(10)); // The date on which solvency will be checked.       
        ///double nShares = 1; // Simulator must be set up so the spot value of the equity is the value of the equity held by the SPV
        ///Share share = new Share(&quot;AAA&quot;, Currency.ZAR);
        ///Dividend dividend = new Dividend(new Share(&quot;AAA&quot;, Currency.ZAR)); // Used for getting the dividend from the model
        ///FloatingIndex jibar = FloatingIndex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BEELoanExample {
            get {
                return ResourceManager.GetString("BEELoanExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BermudanSwaption {
            get {
                object obj = ResourceManager.GetObject("BermudanSwaption", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CDS {
            get {
                object obj = ResourceManager.GetObject("CDS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BermudanSwaption_xlsx,..\..\..\ExcelExamples\BermudanSwaption.xlsx,\Spreadsheets\BermudanSwaption.xlsx
        ///BEELoanExample_cs,..\..\..\Scripts\BermudanSwaption.xlsx,\Scripts\BEELoanExample_cs.
        /// </summary>
        internal static string InstallFileInfo {
            get {
                return ResourceManager.GetString("InstallFileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LogoTemp1_256 {
            get {
                object obj = ResourceManager.GetObject("LogoTemp1_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon LogoTemp1_512 {
            get {
                object obj = ResourceManager.GetObject("LogoTemp1_512", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] QuantSA_dna {
            get {
                object obj = ResourceManager.GetObject("QuantSA_dna", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] QuantSA_Help {
            get {
                object obj = ResourceManager.GetObject("QuantSA_Help", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] QuantSA_xll {
            get {
                object obj = ResourceManager.GetObject("QuantSA_xll", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
